export const districtsLima = [
  { id: 1, name: "Ate" },
  { id: 2, name: "Barranco" },
  { id: 3, name: "Breña" },
  { id: 4, name: "Callao" },
  { id: 5, name: "Cercado de Lima" },
  { id: 6, name: "Chorrillos" },
  { id: 7, name: "La Molina" },
  { id: 8, name: "La Victoria" },
  { id: 9, name: "Lince" },
  { id: 10, name: "Magdalena del Mar" },
  { id: 11, name: "Miraflores" },
  { id: 12, name: "Pueblo Libre" },
  { id: 13, name: "San Borja" },
  { id: 14, name: "San Isidro" },
  { id: 15, name: "San Juan de Lurigancho" },
  { id: 16, name: "San Juan de Miraflores" },
  { id: 17, name: "San Luis" },
  { id: 18, name: "San Martín de Porres" },
  { id: 19, name: "San Miguel" },
  { id: 20, name: "Santiago de Surco" },
  { id: 21, name: "Surquillo" },
  { id: 22, name: "Rímac" },
  { id: 23, name: "Villa El Salvador" },
  { id: 24, name: "Villa María del Triunfo" },
];
